<?php
/**
 * Address Zen - Admin Configuration
 *
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Addresszen\Lookup\ViewModel\AdminConfig $viewModel
 */
$viewModel = $block->getData('view_model');

if (!$viewModel->isEnabled()) {
    return;
}
?>
<script type="text/x-magento-init">
{
    "*": {
        "Addresszen_Lookup/js/address-zen-admin-init": <?= /* @noEscape */ $viewModel->getJsonConfig() ?>
    }
}
</script>
