name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 22

      - name: Cache node modules
        uses: useblacksmith/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Semantic Release
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
